### ISSUE TITLE
String literals should only be passed as `const char*`

### ISSUE THREAD

**Issue by DanRStevens** [Brett208/OP2MissionYukonTrail#7]
Under Mingw, warnings are generated when a string literal is passed to:
```cpp
void DisasterHelper::SendDebugMessage(char* message)
```

Note the `char*` rather than `const char*`. As string literals are `const char*`, and may be stored in read-only memory, any writes to them could crash the process. Hence it is unsafe to pass string literals as simply `char*`, which allows writing. Instead, the method should be declared with a `const char*` parameter type to signify that it does not attempt to modify its argument.

A slight complication, the string is forwarded to Outpost2.exe's `TethtysGame::AddMessage`, which accepts the parameter as `char*` rather than `const char*`. It is not possible to change the declaration in Outpost2DLL, as that would affect name mangling (which it should, since the two types are not freely interchangeable due to write safety).

Assuming Outpost2.exe does not attempt to modify the string, which I believe to be true, you can add a `const_cast` within `DisasterHelper::SendDebugMessage` to cover over the difference.

Suggestion with `const_cast` to cast away the `const`:
```cpp
void DisasterHelper::SendDebugMessage(const char* message)
{
#if _DEBUG
	Unit unit;
	TethysGame::AddMessage(unit, const_cast<char*>(message), PlayerNum::Player0, SoundID::sndBeep8);
#endif
}
```

**Comment by DanRStevens** [comment]
Related, in LevelMain.cpp: line 291:
```cpp
	TethysGame::AddMessage(unit, "Morale is waivering, Good Luck Commander!", playerIndex, SoundID::sndMessage2);
```

This also generates a warning. Again, a `const_cast` around the string to remove the implicit `const` of string literals should fix the warning.

**Comment by Brett208** [comment]
Can we add a function to Outpost2DLL like:

```C++
static void __fastcall TethysGame::AddMessage(Unit owner, const char* message, int toPlayerNum, int soundIndex) {
    // message is passed into outpost 2 as a non const argument. The value of message is not modified by Outpost 2.
    AddMessage(owner, const_cast<char*>(message), toPlayerNum, soundIndex);
}
```

This would keep from having to litter scenario code with const_cast with comments on why it is okay.

If it can't be a part of tethysGame, maybe as a standalone static function?

Thanks,
Brett

**Comment by DanRStevens** [comment]
At present such as upgrade would be more appropriate for OP2Helper than Outpost2DLL. Though there has been some discussion about merging the two (as separate folders in the same project).

Note the entire `TethysGame` class is imported/exported:
```cpp
#ifndef OP2
#define OP2 __declspec(dllimport)
#endif

///...

class OP2 TethysGame {
// ...
```

As such, you wouldn't want to add new methods which don't exist in Outpost2.exe. That's also one of the reasons for the Outpost2DLL / OP2Helper split. Outpost2DLL is just a raw API provided by Outpost2.exe. OP2Helper contains custom helper methods that build on top of that API.

**Comment by Brett208** [comment]
I thought it would be more helpful to be an overload within Outpost2DLL as opposed to a different project, but makes sense that isn't possible. 

It sounds like you are lukewarm about about adding this functionality to OP2Helper?

**Comment by DanRStevens** [comment]
Actually, I would rather welcome something like that to OP2Helper. Perhaps I was stuck in lukewarm mode about adding to Outpost2DLL.

It might make sense to re-order the parameters to better support defaulting. Maybe something like:
```cpp
Unit NullUnit{ 0 };
void AddMessage(const char* message, int soundIndex, int toPlayerNum = 0, Unit source = NullUnit);
```
Might need to think about the defaulting a bit. Is there a default sound?

**Comment by Brett208** [comment]
Why didn't we add NullUnit about 10 years ago to OP2Helper??? That would be a nice touch.

If we want a default message sound effect, it should probably be SoundID::sndMessage2. This is the sound effect when you type a message and press enter to send it to someone else (phone ring type sound). The player would know to check the bottom of the screen for a message if they heard it.

Would you just want to create the function in OP2Helper.h/.cpp?

Thanks,
Brett

**Comment by DanRStevens** [comment]
Lol. I just thought up `NullUnit` while writing that reply. Needed something to assign as a default value, and that parameter seemed least likely to be set, so I figured it had to be last, and so needed a default.

I guess that's why people recommend just doing stuff if you really want to learn how something is done.

Looks like OP2Helper.h/.cpp would be best. Unless you wanted to add new source files.

Also just noticed the EnumSoundId is in OP2Helper, so that's another reason to put this in OP2Helper. :wink:
